CREATE TABLE IF NOT EXISTS permissions (
    id serial PRIMARY KEY,
    title TEXT NOT NULL,
    path TEXT NOT NULL,
    parent_id INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

INSERT INTO permissions (title, path, parent_id, created_at, updated_at) VALUES 
('Moduli', '/', NULL, NOW(), NOW()),
('Finansije', '/finance', 1, NOW(), NOW()),
('Ljudski resursi', '/hr', 1, NOW(), NOW()),
('Osnovna sredstva', '/inventory', 1, NOW(), NOW()),
('Materijalno knjigovodstvo', '/accounting', 1, NOW(), NOW()),
('Javne nabavke', '/procurements', 1, NOW(), NOW()),
('Budžet', '/finance/budget', 2, NOW(), NOW()),
('Trenutni budžet', '/finance/current-budget', 2, NOW(), NOW()),
('Obaveze i potraživanja', '/finance/liabilities-receivables', 2, NOW(), NOW()),
('Računovodstvo', '/finance/accounting', 2, NOW(), NOW()),
('Blagajna', '/finance/cash-register', 2, NOW(), NOW()),
('Depozit', '/finance/deposit', 2, NOW(), NOW()),
('Kazne i takse', '/finance/fines-taxes', 2, NOW(), NOW()),
('Izvještaji', '/finance/reports', 2, NOW(), NOW()),
('Kadrovi', '/hr/employees', 3, NOW(), NOW()),
('Sistematizacija', '/hr/systematization', 3, NOW(), NOW()),
('Sudije', '/hr/judges', 3, NOW(), NOW()),
('Oglasi', '/hr/job-tenders', 3, NOW(), NOW()),
('Preporuke interne revizije', '/hr/revision-recommendations', 3, NOW(), NOW()),
('Izvještaji', '/hr/reports', 3, NOW(), NOW()),
('Pokretna sredstva', '/inventory/movable-inventory', 4, NOW(), NOW()),
('Nepokretna sredstva', '/inventory/immovable-inventory', 4, NOW(), NOW()),
('Sitan inventar', '/inventory/small-inventory', 4, NOW(), NOW()),
('Izvještaji', '/inventory/reports', 4, NOW(), NOW()),
('Planovi', '/procurements/plans', 6, NOW(), NOW()),
('Ugovori', '/procurements/contracts', 6, NOW(), NOW()),
('Izvještaji', '/procurements/reports', 6, NOW(), NOW()),
('Narudžbenica', '/accounting/order-form', 5, NOW(), NOW()),
('Ugovori', '/accounting/contracts', 5, NOW(), NOW()),
('Zalihe robe', '/accounting/stock', 5, NOW(), NOW()),
('Izvještaji', '/accounting/reports', 5, NOW(), NOW()),
('Kreiranje obaveza', '/finance/liabilities-receivables/liabilities', 9, NOW(), NOW()),
('Kreiranje naloga', '/finance/liabilities-receivables/receivables', 9, NOW(), NOW()),
('Stalni depozit', '/finance/deposit/fixed', 12, NOW(), NOW()),
('Prolazni depozit', '/finance/deposit/demand', 12, NOW(), NOW()),
('Kazne', '/finance/fines-taxes/fines', 13, NOW(), NOW()),
('Takse', '/finance/fines-taxes/taxes', 13, NOW(), NOW()),
('Troškovi postupka', '/finance/fines-taxes/procedural-costs', 13, NOW(), NOW()),
('Paušal', '/finance/fines-taxes/flat-rate', 13, NOW(), NOW()),
('Oduzimanje imovinske koristi', '/finance/fines-taxes/confiscation', 13, NOW(), NOW()),
('Unos računa', '/finance/liabilities-receivables/liabilities/invoices', 32, NOW(), NOW()),
('Unos rješenja', '/finance/liabilities-receivables/liabilities/decisions', 32, NOW(), NOW()),
('Unos ugovora', '/finance/liabilities-receivables/liabilities/contracts', 32, NOW(), NOW()),
('Unos zarada', '/finance/liabilities-receivables/liabilities/salaries', 32, NOW(), NOW()),
('Vezani troškovi', '/finance/liabilities-receivables/liabilities/related-expenses', 32, NOW(), NOW()),
('Blagajnički maksimum', '/finance/cash-register/maximum', 11, NOW(), NOW()),
('Zaduženje blagajne', '/finance/cash-register/debt', 11, NOW(), NOW()),
('Finansijski depozit', '/finance/deposit/fixed/finance', 34, NOW(), NOW()),
('Materijalni depozit', '/finance/deposit/fixed/material', 34, NOW(), NOW()),
('Testamentni depozit', '/finance/deposit/fixed/will', 34, NOW(), NOW()),
('Početno stanje', '/finance/deposit/demand/initial-state', 35, NOW(), NOW()),
('Uplata na račun', '/finance/deposit/demand/payment', 35, NOW(), NOW()),
('Obračun poreza i doprinosa', '/finance/deposit/demand/tax-contribution-calculation', 35, NOW(), NOW()),
('Nalozi za plaćanje', '/finance/deposit/demand/payment-orders', 35, NOW(), NOW()),
('Odluka o broju sudija', '/hr/judges/number-decision', 17, NOW(), NOW()),
('Pregled Sudija i predsjednika', '/hr/judges/overview-judges-presidents', 17, NOW(), NOW()),
('Pregled svih oglasa', '/hr/job-tenders/job-tenders-list', 18, NOW(), NOW()),
('Pregled svih kandidata', '/hr/job-tenders/job-tender-applications', 18, NOW(), NOW());